import type { VolunteerTask } from '../types/volunteer';

// Dummy data for volunteer tasks - will be replaced with API data later
export const DUMMY_VOLUNTEER_TASKS: VolunteerTask[] = [
  {
    id: 1,
    imageUri: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
    thumbnailUri: null,
    location: 'MG Road, Near Metro Station, Bangalore',
    concern: 'municipal',
    reportedBy: 'Rahul Sharma',
    reportedAt: '2025-01-03T10:30:00Z',
    status: 'open',
    assignedTo: null,
    assignedAt: null,
    resolvedAt: null,
    resolvedBy: null,
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 1,
        taskId: 1,
        userName: 'Rahul Sharma',
        comment: 'Large pile of garbage near the metro entrance. Has been here for 3 days.',
        createdAt: '2025-01-03T10:30:00Z',
      },
    ],
    statusHistory: [],
    city: 'Bangalore',
    area: 'MG Road',
  },
  {
    id: 2,
    imageUri: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=400',
    thumbnailUri: null,
    location: 'Sector 18, Noida, Near Atta Market',
    concern: 'residential',
    reportedBy: 'Priya Verma',
    reportedAt: '2025-01-02T14:20:00Z',
    status: 'in_progress',
    assignedTo: 'Amit Kumar',
    assignedAt: '2025-01-04T09:00:00Z',
    resolvedAt: null,
    resolvedBy: null,
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 2,
        taskId: 2,
        userName: 'Priya Verma',
        comment: 'Garbage overflow from community bins. Needs immediate attention.',
        createdAt: '2025-01-02T14:20:00Z',
      },
      {
        id: 3,
        taskId: 2,
        userName: 'Amit Kumar',
        comment: 'I am coordinating with the local sanitation team. Will update soon.',
        createdAt: '2025-01-04T09:15:00Z',
      },
    ],
    statusHistory: [
      {
        id: 1,
        taskId: 2,
        previousStatus: 'open',
        newStatus: 'in_progress',
        userName: 'Amit Kumar',
        comment: 'Taking this up. Will coordinate with municipal authorities.',
        createdAt: '2025-01-04T09:00:00Z',
      },
    ],
    city: 'Noida',
    area: 'Sector 18',
  },
  {
    id: 3,
    imageUri: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=400',
    thumbnailUri: null,
    location: 'Connaught Place, Block A, New Delhi',
    concern: 'commercial',
    reportedBy: 'Sneha Gupta',
    reportedAt: '2024-12-28T16:45:00Z',
    status: 'resolved',
    assignedTo: 'Rajesh Singh',
    assignedAt: '2024-12-29T08:00:00Z',
    resolvedAt: '2025-01-01T11:30:00Z',
    resolvedBy: 'Rajesh Singh',
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 4,
        taskId: 3,
        userName: 'Sneha Gupta',
        comment: 'Trash accumulating near the restaurants. Health hazard.',
        createdAt: '2024-12-28T16:45:00Z',
      },
      {
        id: 5,
        taskId: 3,
        userName: 'Rajesh Singh',
        comment: 'Area has been cleaned. Waiting for someone to verify.',
        createdAt: '2025-01-01T11:30:00Z',
      },
    ],
    statusHistory: [
      {
        id: 2,
        taskId: 3,
        previousStatus: 'open',
        newStatus: 'in_progress',
        userName: 'Rajesh Singh',
        comment: 'Starting work on this. Contacted NDMC for support.',
        createdAt: '2024-12-29T08:00:00Z',
      },
      {
        id: 3,
        taskId: 3,
        previousStatus: 'in_progress',
        newStatus: 'resolved',
        userName: 'Rajesh Singh',
        comment: 'Cleanup completed with help from local shopkeepers and NDMC team.',
        createdAt: '2025-01-01T11:30:00Z',
      },
    ],
    city: 'New Delhi',
    area: 'Connaught Place',
  },
  {
    id: 4,
    imageUri: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400',
    thumbnailUri: null,
    location: 'Koramangala 5th Block, Bangalore',
    concern: 'residential',
    reportedBy: 'Vikram Reddy',
    reportedAt: '2024-12-25T09:00:00Z',
    status: 'verified',
    assignedTo: 'Community Volunteers',
    assignedAt: '2024-12-26T07:00:00Z',
    resolvedAt: '2024-12-28T15:00:00Z',
    resolvedBy: 'Community Volunteers',
    verifiedAt: '2024-12-29T10:00:00Z',
    verifiedBy: 'Vikram Reddy',
    comments: [
      {
        id: 6,
        taskId: 4,
        userName: 'Vikram Reddy',
        comment: 'Construction debris dumped on the roadside.',
        createdAt: '2024-12-25T09:00:00Z',
      },
      {
        id: 7,
        taskId: 4,
        userName: 'Community Volunteers',
        comment: 'Debris removed with help from BBMP. Area is now clean.',
        createdAt: '2024-12-28T15:00:00Z',
      },
      {
        id: 8,
        taskId: 4,
        userName: 'Vikram Reddy',
        comment: 'Verified! Great work by the team. The area is completely clean now.',
        createdAt: '2024-12-29T10:00:00Z',
      },
    ],
    statusHistory: [
      {
        id: 4,
        taskId: 4,
        previousStatus: 'open',
        newStatus: 'in_progress',
        userName: 'Community Volunteers',
        comment: 'Local volunteers group taking this up. Will coordinate with BBMP.',
        createdAt: '2024-12-26T07:00:00Z',
      },
      {
        id: 5,
        taskId: 4,
        previousStatus: 'in_progress',
        newStatus: 'resolved',
        userName: 'Community Volunteers',
        comment: 'Task completed. All debris has been cleared and properly disposed.',
        createdAt: '2024-12-28T15:00:00Z',
      },
      {
        id: 6,
        taskId: 4,
        previousStatus: 'resolved',
        newStatus: 'verified',
        userName: 'Vikram Reddy',
        comment: 'I visited the spot and can confirm the cleanup is complete. Thank you!',
        createdAt: '2024-12-29T10:00:00Z',
      },
    ],
    city: 'Bangalore',
    area: 'Koramangala',
  },
  {
    id: 5,
    imageUri: 'https://images.unsplash.com/photo-1567393528677-d6adae7d4a0a?w=400',
    thumbnailUri: null,
    location: 'Andheri West, Near Station Road, Mumbai',
    concern: 'municipal',
    reportedBy: 'Meera Patel',
    reportedAt: '2025-01-05T08:15:00Z',
    status: 'open',
    assignedTo: null,
    assignedAt: null,
    resolvedAt: null,
    resolvedBy: null,
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 9,
        taskId: 5,
        userName: 'Meera Patel',
        comment: 'Open garbage dump causing bad smell and mosquito breeding. Urgent!',
        createdAt: '2025-01-05T08:15:00Z',
      },
    ],
    statusHistory: [],
    city: 'Mumbai',
    area: 'Andheri West',
  },
  {
    id: 6,
    imageUri: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=400',
    thumbnailUri: null,
    location: 'Salt Lake, Sector V, Kolkata',
    concern: 'commercial',
    reportedBy: 'Sourav Das',
    reportedAt: '2025-01-04T12:00:00Z',
    status: 'open',
    assignedTo: null,
    assignedAt: null,
    resolvedAt: null,
    resolvedBy: null,
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 10,
        taskId: 6,
        userName: 'Sourav Das',
        comment: 'E-waste and plastic dumped near IT park. Needs proper disposal.',
        createdAt: '2025-01-04T12:00:00Z',
      },
    ],
    statusHistory: [],
    city: 'Kolkata',
    area: 'Salt Lake',
  },
  {
    id: 7,
    imageUri: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=400',
    thumbnailUri: null,
    location: 'Jubilee Hills, Road No. 36, Hyderabad',
    concern: 'residential',
    reportedBy: 'Arun Reddy',
    reportedAt: '2025-01-01T17:30:00Z',
    status: 'in_progress',
    assignedTo: 'Green Earth NGO',
    assignedAt: '2025-01-02T10:00:00Z',
    resolvedAt: null,
    resolvedBy: null,
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 11,
        taskId: 7,
        userName: 'Arun Reddy',
        comment: 'Garden waste and household garbage mixed. Needs segregation.',
        createdAt: '2025-01-01T17:30:00Z',
      },
      {
        id: 12,
        taskId: 7,
        userName: 'Green Earth NGO',
        comment: 'We are working on segregating and composting the organic waste.',
        createdAt: '2025-01-03T11:00:00Z',
      },
    ],
    statusHistory: [
      {
        id: 7,
        taskId: 7,
        previousStatus: 'open',
        newStatus: 'in_progress',
        userName: 'Green Earth NGO',
        comment: 'Our team has taken up this task. Will demonstrate waste segregation.',
        createdAt: '2025-01-02T10:00:00Z',
      },
    ],
    city: 'Hyderabad',
    area: 'Jubilee Hills',
  },
  {
    id: 8,
    imageUri: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=400',
    thumbnailUri: null,
    location: 'Anna Nagar, Chennai',
    concern: 'municipal',
    reportedBy: 'Lakshmi Iyer',
    reportedAt: '2024-12-30T14:00:00Z',
    status: 'resolved',
    assignedTo: 'Chennai Cleanup Drive',
    assignedAt: '2024-12-31T06:00:00Z',
    resolvedAt: '2025-01-02T18:00:00Z',
    resolvedBy: 'Chennai Cleanup Drive',
    verifiedAt: null,
    verifiedBy: null,
    comments: [
      {
        id: 13,
        taskId: 8,
        userName: 'Lakshmi Iyer',
        comment: 'Drain blocked with garbage causing waterlogging.',
        createdAt: '2024-12-30T14:00:00Z',
      },
      {
        id: 14,
        taskId: 8,
        userName: 'Chennai Cleanup Drive',
        comment: 'Drain cleared and garbage removed. Please verify.',
        createdAt: '2025-01-02T18:00:00Z',
      },
    ],
    statusHistory: [
      {
        id: 8,
        taskId: 8,
        previousStatus: 'open',
        newStatus: 'in_progress',
        userName: 'Chennai Cleanup Drive',
        comment: 'Volunteers mobilized. Starting cleanup early morning.',
        createdAt: '2024-12-31T06:00:00Z',
      },
      {
        id: 9,
        taskId: 8,
        previousStatus: 'in_progress',
        newStatus: 'resolved',
        userName: 'Chennai Cleanup Drive',
        comment: 'Cleanup complete. Drain is now clear and flowing properly.',
        createdAt: '2025-01-02T18:00:00Z',
      },
    ],
    city: 'Chennai',
    area: 'Anna Nagar',
  },
];

// List of cities for filtering
export const CITIES = [
  'All Cities',
  'Bangalore',
  'Mumbai',
  'New Delhi',
  'Noida',
  'Kolkata',
  'Hyderabad',
  'Chennai',
];

// Status options for filtering
export const STATUS_OPTIONS = [
  { label: 'All Status', value: 'all' },
  { label: 'Open', value: 'open' },
  { label: 'In Progress', value: 'in_progress' },
  { label: 'Resolved', value: 'resolved' },
  { label: 'Verified', value: 'verified' },
];

// Status configuration for display
export const VOLUNTEER_STATUS_CONFIG = {
  open: {
    color: '#2196F3', // Blue - info
    label: 'Open',
    icon: 'hand-paper-o',
    description: 'Looking for volunteers',
  },
  in_progress: {
    color: '#FF9800', // Orange - warning
    label: 'In Progress',
    icon: 'spinner',
    description: 'Being worked on',
  },
  resolved: {
    color: '#9C27B0', // Purple
    label: 'Resolved',
    icon: 'check',
    description: 'Awaiting verification',
  },
  verified: {
    color: '#4CAF50', // Green - success
    label: 'Verified',
    icon: 'check-circle',
    description: 'Confirmed fixed',
  },
};
